CREATE TABLE HRM_CONGTY(
	ID INT NOT NULL IDENTITY(1,1), 
	MA_CONG_TY NVARCHAR(20) NOT NULL UNIQUE,
	TEN_CONG_TY NVARCHAR(50) NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_NHAMAY(
	ID INT NOT NULL IDENTITY(1,1),
	MA_NHA_MAY NVARCHAR(20) NOT NULL UNIQUE,
	TEN_NHA_MAY NVARCHAR(50) NOT NULL,
	ID_CONG_TY INT REFERENCES HRM_CONGTY(ID),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_KHOI(
	ID INT NOT NULL IDENTITY(1,1),
	MA_KHOI NVARCHAR(20) NOT NULL UNIQUE,
	TEN_KHOI NVARCHAR(50) NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)

)

CREATE TABLE HRM_PHONGBAN(
	ID INT NOT NULL IDENTITY(1,1),
	MA_PHONG_BAN NVARCHAR(20) NOT NULL UNIQUE,
	TEN_PHONG_BAN NVARCHAR(50) NOT NULL,
	ID_NHA_MAY INT REFERENCES HRM_NHAMAY(ID),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_BOPHAN(
	ID INT NOT NULL IDENTITY(1,1),
	MA_BO_PHAN NVARCHAR(20) NOT NULL UNIQUE,
	TEN_BO_PHAN NVARCHAR(50) NOT NULL,
	ID_PHONG_BAN INT REFERENCES HRM_PHONGBAN(ID),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_CHUCVU(
	ID INT NOT NULL IDENTITY(1,1),
	MA_CHUC_VU NVARCHAR(20) NOT NULL UNIQUE,
	TEN_CHUC_VU NVARCHAR(50) NOT NULL,
	ID_BO_PHAN INT REFERENCES HRM_BOPHAN(ID),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_DANTOC(
	ID INT NOT NULL IDENTITY(1,1),
	TEN_DAN_TOC NVARCHAR(20) NOT NULL,
	GHI_CHU NVARCHAR(50),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_TRANGTHAILAMVIEC(
	ID INT NOT NULL IDENTITY(1,1),
	MA_TRANG_THAI NVARCHAR(20) NOT NULL,
	TEN_TRANG_THAI NVARCHAR(50) NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_TRINHDO(
	ID INT NOT NULL IDENTITY(1,1),
	TEN_TRINH_DO NVARCHAR(50) NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_QUOCTICH(
	ID INT NOT NULL IDENTITY(1,1),
	TEN_QUOC_TICH NVARCHAR(50) NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_BACLUONG(
	ID INT NOT NULL IDENTITY(1,1),
	MA_BAC_LUONG NVARCHAR(20) NOT NULL,
	TEN_BAC_LUONG NVARCHAR(100) NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_TTHONNHAN(
	ID INT NOT NULL IDENTITY(1,1),
	TEN_HON_NHAN NVARCHAR(50) NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_NGOAINGU(
	ID INT NOT NULL IDENTITY(1,1),
	TEN_NGOAI_NGU NVARCHAR(50) NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_TONGIAO(
	ID INT NOT NULL IDENTITY(1,1),
	TEN_TON_GIAO NVARCHAR(50) NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_NHANVIEN(
	ID INT NOT NULL IDENTITY(1,1),
	MA_NHAN_VIEN NVARCHAR(20) NOT NULL UNIQUE,
	TAI_KHOAN NVARCHAR(50) UNIQUE,
	MAT_KHAU NVARCHAR(255),
	HO_TEN NVARCHAR(50) NOT NULL,
	HINH_ANH NVARCHAR(100),
	GIOI_TINH INT NOT NULL,
	NGAY_SINH DATETIME NOT NULL,
	NOI_SINH NVARCHAR(200) NOT NULL,
	CMND NVARCHAR(20) NOT NULL,
	NGAY_CAP DATETIME NOT NULL,
	NOI_CAP NVARCHAR(50) NOT NULL,
	ID_DAN_TOC INT REFERENCES HRM_DANTOC(ID) NOT NULL,
	ID_TON_GIAO INT REFERENCES HRM_TONGIAO(ID),
	ID_QUOC_TICH INT REFERENCES HRM_QUOCTICH(ID) NOT NULL,
	ID_TT_HON_NHAN INT REFERENCES HRM_TTHONNHAN(ID),
	QUE_QUAN NVARCHAR(100) NOT NULL,
	DIA_CHI_THUONG_TRU NVARCHAR(100) NOT NULL,
	NOI_O_HIEN_NAY NVARCHAR(100) NOT NULL,
	DIEN_THOAI NVARCHAR(20) NOT NULL,
	EMAIL NVARCHAR(50),
	ID_NGOAI_NGU INT REFERENCES HRM_NGOAINGU(ID),
	ID_PHONG_BAN INT REFERENCES HRM_PHONGBAN(ID) NOT NULL,
	ID_CHUC_VU INT REFERENCES HRM_CHUCVU(ID) NOT NULL,
	NGAY_VAO_DOAN DATETIME,
	CHUC_VU_DOAN NVARCHAR(20),
	NGAY_VAO_DANG DATETIME,
	CHUC_VU_DANG NVARCHAR(20),
	ID_TRINH_DO INT REFERENCES HRM_TRINHDO(ID) NOT NULL,
	NGANH_DAO_TAO NVARCHAR(50),
	NGAY_VAO_LAM DATETIME,
	ID_TRANG_THAI INT REFERENCES HRM_TRANGTHAILAMVIEC(ID) NOT NULL,
	ACTIVE INT,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_PHANQUYEN(
	ID INT NOT NULL IDENTITY(1,1),
	TEN_QUYEN NVARCHAR(20) NOT NULL,
	ID_NHAN_VIEN INT REFERENCES HRM_NHANVIEN(ID),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_LUONGNHANVIEN(
	ID INT NOT NULL IDENTITY(1,1),
	MA_LUONG_NV NVARCHAR(20) NOT NULL,
	ID_NHAN_VIEN INT NOT NULL,
	ID_BAC_LUONG INT NOT NULL REFERENCES HRM_BACLUONG(ID),
	LUONG_CO_BAN FLOAT NOT NULL,
	PHU_CAP FLOAT NOT NULL,
	LUONG FLOAT NOT NULL,
	TRU_CAC_KHOAN FLOAT,
	LUONG_THUC_LINH FLOAT NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID, ID_NHAN_VIEN),
)

CREATE TABLE HRM_LOAIHOPDONG(
	ID INT NOT NULL IDENTITY(1,1),
	MA_LOAI_HOP_DONG NVARCHAR(20) NOT NULL,
	TEN_LOAI_HOP_DONG NVARCHAR(50) NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_HOPDONGMAU(
	ID INT NOT NULL IDENTITY(1,1),
	MA_HOP_DONG_MAU NVARCHAR(20) NOT NULL,
	TEN_HOP_DONG_MAU NVARCHAR(50) NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_QUATRINHCONGTAC(
	ID INT NOT NULL IDENTITY(1,1),
	MA_QUA_TRINH NVARCHAR(20) NOT NULL,
	ID_NHAN_VIEN INT NOT NULL REFERENCES HRM_NHANVIEN(ID),
	NGAY_BAT_DAU DATETIME NOT NULL,
	NGAY_KET_THUC DATETIME NOT NULL,
	NOI_CONG_TAC NVARCHAR(50) NOT NULL,
	CHUC_VU NVARCHAR(20) NOT NULL,
	MUC_DICH NVARCHAR(50) NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_NHOMQUYETDINH(
	ID INT NOT NULL IDENTITY(1,1),
	MA_NHOM_QD NVARCHAR(20),
	TEN_NHOM_QD NVARCHAR(5),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_LOAIQUYETDINH(
	ID INT NOT NULL IDENTITY(1,1),
	MA_QUYET_DINH NVARCHAR(20),
	TEN_QUYET_DINH NVARCHAR(50),
	ID_NHOM_QD INT NOT NULL REFERENCES HRM_NHOMQUYETDINH(ID),
	GHI_CHU NVARCHAR(255),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_QUYETDINH(
	ID INT NOT NULL IDENTITY(1,1),
	ID_NHAN_VIEN INT NOT NULL REFERENCES HRM_NHANVIEN(ID),
	NGAY_QUYET_DINH DATETIME NOT NULL,
	NGAY_HIEU_LUC DATETIME NOT NULL,
	ID_PHONG_BAN INT REFERENCES HRM_PHONGBAN(ID),
	ID_CHUC_VU INT REFERENCES HRM_CHUCVU(ID),
	ID_LOAI_QD INT REFERENCES HRM_LOAIQUYETDINH(ID)
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_KHENTHUONG(
	ID INT NOT NULL IDENTITY(1,1),
	ID_NHAN_VIEN INT NOT NULL REFERENCES HRM_NHANVIEN(ID),
	NGAY_QUYET_DINH DATETIME NOT NULL,
	HINH_THUC_KHEN_THUONG NVARCHAR(20) NOT NULL,
	LY_DO NVARCHAR(50) NOT NULL,
	GHI_CHU NVARCHAR(100),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_KYLUAT(
	ID INT NOT NULL IDENTITY(1,1),
	ID_NHAN_VIEN INT REFERENCES HRM_NHANVIEN(ID),
	NGAY_QUYET_DINH DATETIME,
	HINH_THUC_KY_LUAT NVARCHAR(20),
	LYDO NVARCHAR(50),
	GHICHU NVARCHAR(100),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

--CREATE TABLE HRM_THAISAN(
--	ID INT NOT NULL IDENTITY(1,1),
--	ID_NHAN_VIEN INT REFERENCES HRM_NHANVIEN(ID),
--	SINH_CON_THU INT NOT NULL,
--	NGAY_BAT_DAU DATETIME NOT NULL,
--	NGAY_KET_THUC DATETIME NOT NULL,
--	NOI_DUNG NVARCHAR(50),
--	GHI_CHU NVARCHAR(100),
--	PRIMARY KEY(ID)
--)

CREATE TABLE HRM_TAISANNHANVIEN(
	ID INT NOT NULL IDENTITY(1,1),
	MA_TAI_SAN NVARCHAR(20) NOT NULL,
	ID_NHAN_VIEN INT REFERENCES HRM_NHANVIEN(ID),
	TEN_TAI_SAN NVARCHAR(50) NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_BANGIAONGHIVIEC(
	ID INT NOT NULL IDENTITY(1,1),
	MA_BAN_GIAO NVARCHAR(20) NOT NULL,
	ID_NHAN_VIEN INT REFERENCES HRM_NHANVIEN(ID),
	ID_TAI_SAN INT REFERENCES HRM_TAISANNHANVIEN(ID),
	TRANG_THAI INT
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_THONGTINGIADINH(
	ID INT NOT NULL IDENTITY(1,1),
	ID_NHAN_VIEN INT NOT NULL REFERENCES HRM_NHANVIEN(ID),
	HO_TEN NVARCHAR(50) NOT NULL,
	MOI_QUAN_HE NVARCHAR(50) NOT NULL,
	NAM_SINH DATETIME NOT NULL,
	QUE_QUAN NVARCHAR(100) NOT NULL,
	NOI_O_HIEN_NAY NVARCHAR(100) NOT NULL,
	NGHE_NGHIEP NVARCHAR(50),
	DON_VI_CONG_TAC NVARCHAR(50),
	CHUC_VU NVARCHAR(50),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_NGHIVIEC(
	ID INT NOT NULL IDENTITY(1,1),
	ID_NHAN_VIEN INT NOT NULL REFERENCES HRM_NHANVIEN(ID),
	NGAY_THOI_VIEC DATETIME NOT NULL,
	LY_DO_THOI_VIEC NVARCHAR(255) NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID, ID_NHAN_VIEN)
)

CREATE TABLE HRM_HOPDONG(
	ID INT NOT NULL IDENTITY(1,1),
	MA_HOP_DONG NVARCHAR(20) NOT NULL UNIQUE,
	ID_NHAN_VIEN INT NOT NULL REFERENCES HRM_NHANVIEN(ID),
	NGAY_BAT_DAU DATETIME NOT NULL,
	NGAY_KET_THUC DATETIME NOT NULL,
	DIA_DIEM_LAM_VIEC NVARCHAR(50) NOT NULL,
	PHU_CAP FLOAT NOT NULL,
	CHUC_VU NVARCHAR(20),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID, ID_NHAN_VIEN)
)

CREATE TABLE HRM_BAOHIEM(
	ID INT NOT NULL IDENTITY(1,1),
	ID_NHAN_VIEN INT NOT NULL REFERENCES HRM_NHANVIEN(ID),
	MA_BAO_HIEM NVARCHAR(50),
	LOAI_BAO_HIEM NVARCHAR(20),
	THOI_GIAN DATETIME,
	TY_LE_DONG FLOAT,
	MUC_LUONG_DONG_BN FLOAT,
	LOAI_PHAT_SINH NVARCHAR(50)
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_TUYENDUNG(
	ID INT NOT NULL IDENTITY(1,1),
	VI_TRI_TUYEN_DUNG NVARCHAR(50) NOT NULL,
	ID_NHA_MAY INT REFERENCES HRM_NHAMAY(ID),
	ID_PHONG_BAN INT REFERENCES HRM_PHONGBAN(ID),
	ID_CHUC_VU INT REFERENCES HRM_CHUCVU(ID),
	YEU_CAU_TUYEN_DUNG NVARCHAR(255) NOT NULL,
	SO_LUONG_TUYEN INT NOT NULL,
	GHI_CHU NVARCHAR(100),
	THOI_GIAN_BAT_DAU DATETIME NOT NULL,
	THOI_GIAN_KET_THUC DATETIME NOT NULL,
	CHI_PHI FLOAT,
	KINH_NGHIEM_LAM_VIEC NVARCHAR(255),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_HOSOUNGVIEN(
	ID INT NOT NULL IDENTITY(1,1),
	MA_UNG_VIEN NVARCHAR(20) NOT NULL UNIQUE,
	HO_TEN NVARCHAR(50) NOT NULL,
	HINH_ANH NVARCHAR(100),
	GIOI_TINH INT NOT NULL,
	NGAY_SINH DATETIME NOT NULL,
	NOI_SINH NVARCHAR(200) NOT NULL,
	CMND NVARCHAR(20) NOT NULL,
	NGAY_CAP DATETIME NOT NULL,
	NOI_CAP NVARCHAR(50) NOT NULL,
	MA_DAN_TOC INT REFERENCES HRM_DANTOC(ID),
	ID_TON_GIAO INT REFERENCES HRM_TONGIAO(ID),
	MA_QUOC_TICH INT REFERENCES HRM_QUOCTICH(ID),
	ID_TT_HON_NHAN INT REFERENCES HRM_TTHONNHAN(ID),
	QUE_QUAN NVARCHAR(100) NOT NULL,
	DIA_CHI_THUONG_TRU NVARCHAR(100) NOT NULL,
	NOI_O_HIEN_NAY NVARCHAR(100) NOT NULL,
	DIEN_THOAI NVARCHAR(20) NOT NULL,
	EMAIL NVARCHAR(50),
	NGAY_VAO_DOAN DATETIME,
	CHUC_VU_DOAN NVARCHAR(20),
	NGAY_VAO_DANG DATETIME,
	CHUC_VU_DANG NVARCHAR(20),
	MA_TRINH_DO INT REFERENCES HRM_TRINHDO(ID),
	NGANH_DAO_TAO NVARCHAR(50),
	MA_TUYEN_DUNG INT REFERENCES HRM_TUYENDUNG(ID),
	ID_NGOAI_NGU INT REFERENCES HRM_NGOAINGU(ID),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_QUATRINHTUYENDUNG(
	ID INT NOT NULL IDENTITY(1,1),
	THOI_GIAN_PV DATETIME NOT NULL,
	ID_UNG_VIEN INT REFERENCES HRM_HOSOUNGVIEN(ID),
	DIA_DIEM_PV NVARCHAR(50) NOT NULL,
	NGUOI_PV NVARCHAR(20) NOT NULL,
	KET_QUA INT,
	GHI_CHU NVARCHAR(255),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_KETQUATUYENDUNG(
	ID INT NOT NULL IDENTITY(1,1),
	MA_UNG_VIEN INT REFERENCES HRM_HOSOUNGVIEN(ID),
	ID_NHAN_VIEN INT REFERENCES HRM_NHANVIEN(ID),
	ID_PHONG_BAN INT REFERENCES HRM_PHONGBAN(ID),
	ID_CHUC_VU INT REFERENCES HRM_CHUCVU(ID),
	NGAY_TUYEN_DUNG DATETIME,
	ID_TUYEN_DUNG INT REFERENCES HRM_QUATRINHTUYENDUNG(ID),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID, ID_NHAN_VIEN)
)

CREATE TABLE HRM_LOAINGHIPHEP(
	ID INT NOT NULL IDENTITY(1,1),
	TIEU_DE_NGHI_PHEP NVARCHAR(50) NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_CHITIETLOAINGHIPHEP(
	ID INT NOT NULL IDENTITY(1,1),
	TEN_CHI_TIET NVARCHAR(50),
	SO_NGAY_NGHI INT,
	ID_NGHI_PHEP INT REFERENCES HRM_LOAINGHIPHEP(ID),
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_LUUTRUPHEP(
	ID INT NOT NULL IDENTITY(1,1),
	ID_NHAN_VIEN INT REFERENCES HRM_NHANVIEN(ID),
	SO_THANG_LAM_VIEC INT,
	DA_SU_DUNG INT,
	ID_CHI_TIET_NGHI_PHEP INT REFERENCES HRM_CHITIETLOAINGHIPHEP(ID),
	SO_PHEP_THUC_TE INT,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID, ID_NHAN_VIEN)
)

CREATE TABLE HRM_XINNGHIPHEP(
	ID INT NOT NULL IDENTITY(1,1),
	ID_NHAN_VIEN INT NOT NULL REFERENCES HRM_NHANVIEN(ID),
	ID_BO_PHAN INT NOT NULL,
	ID_CHUC_VU INT NOT NULL,
	NGUOI_DUYET INT NOT NULL,
	TU_NGAY DATETIME NOT NULL,
	DEN_NGAY DATETIME NOT NULL,
	LY_DO NVARCHAR(255) NOT NULL,
	SO_NGAY_NGHI INT NOT NULL,
	GHI_CHU NVARCHAR(255),
	TRANG_THAI INT NOT NULL,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_PHEPTON(
	ID INT NOT NULL IDENTITY(1,1),
	ID_NHAN_VIEN INT NOT NULL REFERENCES HRM_NHANVIEN(ID),
	PHEP_TON INT,
	NAM_TON INT,
	NGUOI_TAO INT NOT NULL,
	NGUOI_SUA INT NOT NULL,
	NGAY_TAO DATETIME NOT NULL,
	NGAY_SUA DATETIME NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_DIEUCHUYENNHANSU(
	ID INT NOT NULL IDENTITY(1,1),
	ID_QUYET_DINH INT REFERENCES HRM_QUYETDINH(ID),
	NGAY_DIEU_CHUYEN DATETIME NOT NULL,
	ID_NHAN_VIEN INT NOT NULL REFERENCES HRM_NHANVIEN(ID),
	PHONG_BAN_HIEN_TAI INT REFERENCES HRM_PHONGBAN(ID),
	CHUC_VU_HIEN_TAI INT REFERENCES HRM_CHUCVU(ID),
	LUONG_HIEN_TAI FLOAT,
	LUONG_DIEU_CHUYEN FLOAT,
	PHONG_BAN_DIEU_CHUYEN INT REFERENCES HRM_PHONGBAN(ID),
	CHUC_VU_DIEU_CHUYEN INT REFERENCES HRM_CHUCVU(ID),
	GHI_CHU NVARCHAR(255)
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_THONGBAO(
	ID INT NOT NULL IDENTITY(1,1),
	ID_NHAN_VIEN INT NOT NULL REFERENCES HRM_NHANVIEN(ID),
	TIEU_DE NVARCHAR(50),
	NOI_DUNG NVARCHAR(255),
	TRANG_THAI INT
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_DAOTAO(
	ID INT NOT NULL IDENTITY(1,1),
	MA_DAO_TAO NVARCHAR(20) NOT NULL,
	TEN_KHOA_DAO_TAO NVARCHAR(100) NOT NULL,
	TU_NGAY DATETIME NOT NULL,
	DEN_NGAY DATETIME NOT NULL,
	DIA_DIEM NVARCHAR(50),
	ID_PHONG_BAN INT REFERENCES HRM_PHONGBAN(ID),
	GHI_CHU NVARCHAR(255)
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_DANHSACHDAOTAO(
	ID INT NOT NULL IDENTITY(1,1),
	ID_DAO_TAO INT REFERENCES HRM_DAOTAO(ID),
	MA_NHAN_VIEN NVARCHAR(20) NOT NULL,
	TEN_NHAN_VIEN NVARCHAR(50) NOT NULL,
	CHUC_VU NVARCHAR(20) NOT NULL,
	PHONG_BAN NVARCHAR(50) NOT NULL,
	DIEN_THOAI NVARCHAR(11) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	KET_QUA NVARCHAR(20),
	NHAN_XET NVARCHAR(255)
	PRIMARY KEY(ID)
)

CREATE TABLE HRM_CHIPHIDAOTAO(
	ID INT NOT NULL IDENTITY(1,1),
	ID_DAO_TAO INT REFERENCES HRM_DAOTAO(ID),
	MA_CHI_PHI NVARCHAR(20),
	TEN_CHI_PHI NVARCHAR(50),
	CHI_PHI FLOAT
	PRIMARY KEY(ID)
)